Adding stream feature with StreamingClient

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -2,9 +2,9 @@ name: Rust
 
 on:
   push:
-    branches: [ "master" ]
+    branches: ["master"]
   pull_request:
-    branches: [ "master" ]
+    branches: ["master"]
 
 env:
   CARGO_TERM_COLOR: always
@@ -14,25 +14,25 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-    
-    # Step to spin up the Gotenberg Docker container
-    - name: Start Gotenberg Docker container
-      run: docker run -d -p 3000:3000 gotenberg/gotenberg:8
+      - uses: actions/checkout@v4
 
-    # Step to verify Gotenberg container is reachable
-    - name: Check Gotenberg container is reachable
-      run: |
-        for i in {1..10}; do
-          if curl --silent --head http://localhost:3000/; then
-            echo "Gotenberg is reachable!";
-            exit 0;
-          fi
-          echo "Waiting for Gotenberg...";
-          sleep 3;
-        done
-        echo "Failed to reach Gotenberg";
-        exit 1
+      # Step to spin up the Gotenberg Docker container
+      - name: Start Gotenberg Docker container
+        run: docker run -d -p 3000:3000 gotenberg/gotenberg:8
 
-    - name: Run tests
-      run: cargo test --verbose
+      # Step to verify Gotenberg container is reachable
+      - name: Check Gotenberg container is reachable
+        run: |
+          for i in {1..10}; do
+            if curl --silent --head http://localhost:3000/; then
+              echo "Gotenberg is reachable!";
+              exit 0;
+            fi
+            echo "Waiting for Gotenberg...";
+            sleep 3;
+          done
+          echo "Failed to reach Gotenberg";
+          exit 1
+
+      - name: Run tests
+        run: cargo test --features "stream"
